backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  name: github
  repo: saiminh/CWN-netlifycms-eleventy
media_folder: "src/static/img"
public_folder: "/static/img"
# site_url: "https://www.cookingwithnothing.com"
# display_url: "https://www.cookingwithnothing.com"
logo_url: "https://cookingwithnothing.com/static/img/cwn-logo.svg"
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "pages"
    folder: "src/_content/pages"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Feature Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string", description: "SEO stuff, also what shows up on a google result", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Blog"
    name: "blog"
    folder: "src/_content/posts"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Feature Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string", description: "SEO stuff, also what shows up on a google result", required: true }
      - { label: "Author", name: "author", widget: "string", required: false  }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          search_fields:
            - "tags.*.name"
          display_fields:
            - "tags.*.name"
          value_field: "tags.*.slug"
          multiple: true
  - label: "Recipes"
    name: "recipes"
    folder: "src/_content/recipes"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Feature Image", name: "featuredImage", widget: "image" }
      - { label: "Description", name: "description", widget: "string", description: "SEO stuff, also what shows up on a google result", required: true }
      - { label: "Author", name: "author", widget: "string", required: false  }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Ingredients", name: "ingredients", widget: "markdown", required: false }
      - { label: "Instructions", name: "instructions", widget: "markdown", required: false }
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          search_fields:
            - "tags.*.name"
          display_fields:
            - "tags.*.name"
          value_field: "tags.*.slug"
          multiple: true
  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "tags"
        label: "Tags"
        file: "src/_data/mytags.yaml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Tooltip, name: tooltip, widget: string }
